// Generated by ts-to-zod
import { z } from "zod";
import { OrderState } from "./models";

export const orderStateSchema = z.enum(OrderState);

export const customerSchema = z.object({
    id: z.string(),
    name: z.string(),
    country: z.string(),
    createdAt: z.string(),
    lastOrderAt: z.string().nullable()
});

export const lineItemSchema = z.object({
    productId: z.string(),
    name: z.string(),
    quantity: z.number(),
    price: z.number().describe("Unit price in base currency units (e.g. cents)")
});

export const orderSchema = z.object({
    id: z.string(),
    customerId: z.string(),
    state: orderStateSchema,
    currency: z.string(),
    amount: z.number().describe("Total order amount in base currency units (e.g. cents)"),
    createdAt: z.string(),
    completedAt: z.string().nullable(),
    lineItems: z.array(lineItemSchema)
});
